package application;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.input.MouseDragEvent;

import javafx.scene.input.MouseEvent;
import javafx.scene.paint.Color;
import javafx.scene.canvas.Canvas;

import javafx.scene.input.DragEvent;
import javafx.scene.input.MouseButton;

public class SampleController {
	@FXML
	private Canvas CanvFX;
	@FXML
	private Button but;

//--------------------------------------------------------------------------
	@FXML
	public void onMouseDragged(MouseEvent event) {
		// TODO Autogenerated
		//System.out.println("MouseD"+event.getButton().toString());
		System.out.println("Mouse "+event.getButton().toString()+" Pos=("+event.getX()+","+event.getY()+")");
		if(event.getButton()==MouseButton.PRIMARY){
			ShowDotG(event.getX(),event.getY(),Color.BLACK);
		}	
	}
	
	private double curX=0,curY=0;
	private double dotSize=30;
	private int numDotX;
	private int numDotY;
	class myDot{
		private double dotX,dotY;
		private Color c=Color.TRANSPARENT;
		private int neighbors=-1;
		private boolean exists=false;
	}
	private myDot[][] myDots;
	private myDot testDot;
	//private double curX=0,curY=0;
		private void ShowDotG(double x, double y,Color c) {
		// TODO Auto-generated method stub
		//double dotSize=20;

		double dotX,dotY;
		CanvFX.getGraphicsContext2D().setFill(c);
		System.out.printf("mouse %g %g\n",x,y);
		System.out.printf("curre %g %g\n",curX,curY);

		if(Math.abs(curX-x)>dotSize & Math.abs(curY-y)>dotSize){
			System.out.printf("------------------------------- %g %g",x,y);
			curX=x;
			curY=y;
			//CanvFX.getGraphicsContext2D().fillRect(x, y, dotSize, dotSize);
		}
		//CanvFX.getGraphicsContext2D().clearRect(0, 0, CanvFX.getWidth(), CanvFX.getHeight());
	}
	// Event Listener on ImageView.onMouseClicked
	@FXML
	public void onMonkey(MouseEvent event) {
		// TODO Autogenerated
		if(event.getButton()==MouseButton.PRIMARY){
			System.out.println("LeftMonkey");
		}
		if(event.getButton()==MouseButton.SECONDARY){
			System.out.println("RightMonkey");
		}
	}
	
	// Event Listener on Button[#but].onMouseClicked
	@FXML
	public void onBut(MouseEvent event) {
		// TODO Autogenerated
		System.out.println("ButClick");
		CanvFX.getGraphicsContext2D().clearRect(0, 0, CanvFX.getWidth(), CanvFX.getHeight());
	}

//------------------------------------------------------------------------------
	 @FXML
    public void initialize() {
			System.out.println("init");
			numDotX=(int)CanvFX.getWidth();
			numDotX=(int) (((int)CanvFX.getWidth())/dotSize);
			numDotY=(int) (((int)CanvFX.getHeight())/dotSize);
			myDots=new myDot[numDotX][numDotY];
			for(int i=0;i<numDotX;i++){
				for(int j=0;j<numDotY;j++){
					myDots[i][j]=new myDot();
				}
			}
			//CanvFX.getGraphicsContext2D().clearRect(0, 0, CanvFX.getWidth(), CanvFX.getHeight());
	 }	

	 public SampleController(){
		System.out.println("Constr");		
	}

//------------------------------------------------------------------------------

}
