package application;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.input.MouseDragEvent;

import javafx.scene.input.MouseEvent;
import javafx.scene.paint.Color;
import javafx.scene.canvas.Canvas;

import javafx.scene.input.DragEvent;
import javafx.scene.input.MouseButton;

public class SampleController {
	@FXML
	private Canvas CanvFX;
	@FXML
	private Button but;
	@FXML
	private Button but1;
	@FXML
	private Button but2;

//--------------------------------------------------------------------------
	@FXML
	public void onMouseDragged(MouseEvent event) {
		// TODO Autogenerated
		//System.out.println("MouseD"+event.getButton().toString());
		System.out.println("Mouse "+event.getButton().toString()+" Pos=("+event.getX()+","+event.getY()+")");
		if(event.getButton()==MouseButton.PRIMARY){
			ShowDotG(event.getX(),event.getY(),Color.BLACK);
		}	
	}
	
	private double curX=0,curY=0;
	private double dotSize=10;
	private int numDotX;
	private int numDotY;
	class myDot{
		private double dotX,dotY;
		private Color c=Color.TRANSPARENT;
		private int neighbors=-1;
		private boolean exists=false;
	}
	private myDot[][] myDots;
	//private myDot testDot;
	//private double curX=0,curY=0;
	
	private void ShowGeneration(Color c){
		CanvFX.getGraphicsContext2D().setFill(c);
		for(int i=0;i<numDotX;i++){
			for(int j=0;j<numDotY;j++){
				if(myDots[i][j].exists){
					CanvFX.getGraphicsContext2D().fillRect(i*dotSize,j*dotSize,dotSize,dotSize);
				}
			}
		}
	}

	private void ClearGeneration(){
		CanvFX.getGraphicsContext2D().setFill(Color.TRANSPARENT);
		for(int i=0;i<numDotX;i++){
			for(int j=0;j<numDotY;j++){
				if(myDots[i][j].exists){
					CanvFX.getGraphicsContext2D().clearRect(i*dotSize,j*dotSize,dotSize,dotSize);
	//				CanvFX.getGraphicsContext2D().clearRect(0, 0, CanvFX.getWidth(), CanvFX.getHeight());
					myDots[i][j].exists=false;
				}
			}
		}
	}

	private void ShowDotG(double x, double y,Color c) {
			// TODO Auto-generated method stub
			//double dotSize=20;
	
			//double dotX,dotY;
			CanvFX.getGraphicsContext2D().setFill(c);
			curX=(int)(x/dotSize);
			curY=(int)(y/dotSize);
			CanvFX.getGraphicsContext2D().fillRect(curX*dotSize, curY*dotSize, dotSize, dotSize);
			myDots[(int)curX][(int)curY].exists=true;
			
			
	/*
	 		boolean delta=Math.abs(curX-x)>dotSize | Math.abs(curY-y)>dotSize;
			double deltaX=Math.abs(curX-x);
			double deltaY=Math.abs(curY-y);
			System.out.printf("mouse  (%g %g) curre ( %g %g)  ( %g %g) %g %b\n",x,y,curX,curY, deltaX, deltaY,dotSize, delta);
			if(! myDots[(int)(x/dotSize)][(int)(x/dotSize)].exists)
			{
				CanvFX.getGraphicsContext2D().fillRect(curX, curY, dotSize, dotSize);			
			}
			if(Math.abs(curX-x)>dotSize | Math.abs(curY-y)>dotSize){
				System.out.printf("------------------------------- %g %g \n",x,y);
				curX=((int)(x/dotSize))*dotSize;
				curY=((int)(y/dotSize))*dotSize;
				CanvFX.getGraphicsContext2D().fillRect(curX, curY, dotSize, dotSize);
			}
			//CanvFX.getGraphicsContext2D().clearRect(0, 0, CanvFX.getWidth(), CanvFX.getHeight());
	*/	
	}
	// Event Listener on ImageView.onMouseClicked
	@FXML
	public void onMonkey(MouseEvent event) {
		// TODO Autogenerated
		if(event.getButton()==MouseButton.PRIMARY){
			System.out.println("LeftMonkey");
		}
		if(event.getButton()==MouseButton.SECONDARY){
			System.out.println("RightMonkey");
		}
	}
	// Event Listener on Button[#but].onMouseClicked
	@FXML
	public void onBut(MouseEvent event) {
		// TODO Autogenerated
		System.out.println("ButClick");
		CanvFX.getGraphicsContext2D().clearRect(0, 0, CanvFX.getWidth(), CanvFX.getHeight());
	}

	@FXML
	public void onBut1(MouseEvent event) {
		// TODO Autogenerated
		System.out.println("But1Click");
		ShowGeneration(Color.BLUEVIOLET);
		//		CanvFX.getGraphicsContext2D().clearRect(0, 0, CanvFX.getWidth(), CanvFX.getHeight());
	}

	@FXML
	public void onBut2(MouseEvent event) {
		// TODO Autogenerated
		System.out.println("But2Click");
		ClearGeneration();
		//		CanvFX.getGraphicsContext2D().clearRect(0, 0, CanvFX.getWidth(), CanvFX.getHeight());
	}
//------------------------------------------------------------------------------
	 @FXML
    public void initialize() {
			System.out.println("init");
			numDotX=(int)CanvFX.getWidth();
			numDotX=(int) (((int)CanvFX.getWidth())/dotSize);
			numDotY=(int) (((int)CanvFX.getHeight())/dotSize);
			myDots=new myDot[numDotX][numDotY];
			for(int i=0;i<numDotX;i++){
				for(int j=0;j<numDotY;j++){
					myDots[i][j]=new myDot();
				}
			}
			//CanvFX.getGraphicsContext2D().clearRect(0, 0, CanvFX.getWidth(), CanvFX.getHeight());
	 }	

	public SampleController(){
		System.out.println("Constr");
	}

//------------------------------------------------------------------------------

}
