package application;

import javafx.animation.KeyFrame;
import javafx.animation.KeyValue;
import javafx.animation.Timeline;
import javafx.fxml.FXML;

import javafx.scene.layout.AnchorPane;
import javafx.util.Duration;
import javafx.scene.input.MouseButton;
import javafx.scene.input.MouseEvent;

import javafx.scene.canvas.Canvas;

public class SampleController {
	@FXML
	private AnchorPane mainPane;
	@FXML
	private AnchorPane greenPane;
	@FXML
	private AnchorPane tanPane;
	@FXML

	//--------------------------------------------------------------------

	private Canvas tanCanvas;

	// Event Listener on AnchorPane[#mainPane].onMouseClicked
	@FXML
	public void onGroupMouseClick(MouseEvent event) {
		// TODO Autogenerated
		if(event.getButton() == MouseButton.PRIMARY){
			System.out.println("1111111111111111111111111111111111111111111");
			if(event.getX()<800.0 & event.getY()>260){
				Timeline timeline1 = new Timeline();
				double durTime=1000;
				KeyFrame key11 = new KeyFrame(Duration.millis(durTime),
								new KeyValue (tanPane.prefWidthProperty(), 804)); 
				timeline1.getKeyFrames().add(key11); 
				
				KeyFrame key21 = new KeyFrame(Duration.millis(durTime),
								 new KeyValue (tanPane.prefHeightProperty(), 804)); 
				timeline1.getKeyFrames().add(key21); 
				//timeline1.play();
/*				
				//Timeline timeline2 = new Timeline();
				KeyFrame key23 = new KeyFrame(Duration.millis(durTime),
								 new KeyValue (greenPane.prefWidthProperty(), 804)); 
				timeline1.getKeyFrames().add(key23); 
		
				KeyFrame key24 = new KeyFrame(Duration.millis(durTime),
						 new KeyValue (greenPane.prefHeightProperty(), 120)); 
				timeline1.getKeyFrames().add(key24); 
		
				timeline1.setOnFinished((ae) -> System.exit(0)); 

*/				
				timeline1.play();
				
			}		
		}
		if(event.getButton() == MouseButton.SECONDARY){
			
			System.out.println("22222222222222222222222222222222222222222222=("+event.getX()+" ; "+event.getY()+")");
			if(event.getX()<800.0 & event.getY()>260){
				Timeline timeline2 = new Timeline();
				KeyFrame key2 = new KeyFrame(Duration.millis(1500),
								new KeyValue (mainPane.getScene().getRoot().opacityProperty(), 0)); 
				timeline2.getKeyFrames().add(key2); 
/*	
            KeyFrame key2 = new KeyFrame(Duration.millis(3000),
                    new KeyValue (primaryStage.getScene().getRoot().opacityProperty(), 1)); 
            timeline.getKeyFrames().add(key2);  
*/
				timeline2.setOnFinished((ae) -> System.exit(0)); 
				timeline2.play();
			}
		}
		if(event.getButton() == MouseButton.MIDDLE){
			System.out.println("333333333333333333333333333333333333333333333");
		}
	}

	//--------------------------------------------------------------------
	
}
