package application;

import javafx.fxml.FXML;

import javafx.scene.layout.AnchorPane;
import javafx.scene.input.MouseButton;
import javafx.scene.input.MouseEvent;

import javafx.scene.canvas.Canvas;

public class SampleController {
	@FXML
	private AnchorPane mainPane;
	@FXML
	private AnchorPane greenPane;
	@FXML
	private AnchorPane tanPane;
	@FXML
	private Canvas tanCanvas;

	// Event Listener on AnchorPane[#mainPane].onMouseClicked
	@FXML
	public void onGroupMouseClick(MouseEvent event) {
		// TODO Autogenerated
		if(event.getButton() == MouseButton.PRIMARY){
			System.out.println("1111111111111111111111111111111111111111111");
		}
		if(event.getButton() == MouseButton.SECONDARY){
			System.out.println("22222222222222222222222222222222222222222222");
		}
		if(event.getButton() == MouseButton.MIDDLE){
			System.out.println("333333333333333333333333333333333333333333333");
		}
	}
}
